plcAddress = "192.168.140.13"
plcMode = "REAL"
cameraURL = "ftp://admin@192.168.140.19/image.bmp"
pixelsPer_mm = 18
manualCalibrationOffsetUX = 65.0
manualCalibrationOffsetUY = -108.2
manualCalibrationOffsetVX = 65.0
manualCalibrationOffsetVY = -108.2
manualCalibrationOffsetXX = 65.0
manualCalibrationOffsetXY = -108.2
manualCalibrationOffsetGX = 65.0
manualCalibrationOffsetGY = -108.2
serverAddress = "127.0.0.1"
serverPort = 6626
webServerPort = 8080
machineCalibrationFile = "machineCalibration.json"
maxVelocity = 1020
maxSlowVelocity = 25.4
maxAcceleration = 2000
maxDeceleration = 2000
maxJerkAccel = 1500.0
maxJerkDecel = 1500.0
